name: unit-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: |
          dotnet restore src/WebApp/WebApp.csproj
          dotnet restore tests/WebApp.Tests/WebApp.Tests.csproj

      - name: Build
        run: |
          dotnet build src/WebApp/WebApp.csproj -c Release --no-restore
          dotnet build tests/WebApp.Tests/WebApp.Tests.csproj -c Release --no-restore

      - name: Test
        run: dotnet test tests/WebApp.Tests/WebApp.Tests.csproj -c Release --no-build --collect "XPlat Code Coverage"
